# action.yml
name: 'MCIX datastage import action'
author: 'Data Migrators Pty Ltd'
description: 'Runs mcix datastage import'
inputs:

  api-key:
    description: 'API key for authentication'
    required: true

  url:
    description: 'URL of the DataStage server'
    required: true

  user:
    description: 'Username for authentication'
    required: true

  assets:
    description: 'Path to the DataStage assets to import'
    required: true
    default: ""

  project:
    description: 'DataStage project name'
    required: false     # Required when -project-id not specified
    default: ""

  project-id:
    description: 'DataStage project id'
    required: false     # Required when -project not specified
    default: ""

outputs:
  return-code:
    description: 'The return code of the command'


branding:
  icon: 'log-in'
  color: 'blue'
