# action.yml
name: 'MCIX asset-analysis query action'
author: 'Data Migrators Pty Ltd'
description: 'Runs mcix asset-analysis query'
# No inputs currently required for this action

# **Will** eventually take the following arguments:
#    inputs:
#
#      name: assets
#        description: Location of all json assets to query
#        required: true
#
#      name: exclude-tag
#        description: Tags of asset queries to exclude (case insensitive) (repeatable)
#        required: false
#
#      name: include-tag
#        description: Tags of asset queries to include (case insensitive), includes everything by default (case insensitive) (repeatable)
#        required: false
#
#      name: queries
#        description: Location of all the query files
#        required: false
#
#      name: report
#        description: Report name (.csv)
#        required: false
#
#      name: threads
#        description: Number of threads of execution
#        default: 1

outputs:
  return-code:
    description: 'The return code of the command'

runs:
  using: 'docker'
  image: 'Dockerfile' # Refers to the Dockerfile in the current directory

branding:
  icon: 'x'
  color: 'red'
